// Package stubassets embeds the pre-compiled extractor stub binaries so the
// builder can produce self-extracting archives without invoking the Go
// toolchain at pack time. The stubs are generated by build/build-stubs.sh.
package stubassets

import (
	"embed"
	"fmt"
)

//go:embed stubs
var stubsFS embed.FS

// Target describes one buildable output platform.
type Target struct {
	// Key is a stable identifier used on the CLI (e.g. "windows-amd64").
	Key string
	// Label is a human-friendly name for the GUI.
	Label  string
	GOOS   string
	GOARCH string
	// OutExt is appended to the output file name (".exe" on Windows).
	OutExt string
	// UnixExec marks the output executable (chmod +x) for macOS/Linux.
	UnixExec bool
}

// stubFile is the embedded file name for a target.
func (t Target) stubFile() string {
	name := "loci-stub-" + t.GOOS + "-" + t.GOARCH
	if t.GOOS == "windows" {
		name += ".exe"
	}
	return name
}

// Targets is the set of platforms the builder can emit.
var Targets = []Target{
	{Key: "windows-amd64", Label: "Windows (64-bit)", GOOS: "windows", GOARCH: "amd64", OutExt: ".exe", UnixExec: false},
	{Key: "macos-arm64", Label: "macOS (Apple Silicon)", GOOS: "darwin", GOARCH: "arm64", OutExt: "", UnixExec: true},
	{Key: "macos-amd64", Label: "macOS (Intel)", GOOS: "darwin", GOARCH: "amd64", OutExt: "", UnixExec: true},
	{Key: "linux-amd64", Label: "Linux (64-bit)", GOOS: "linux", GOARCH: "amd64", OutExt: "", UnixExec: true},
}

// TargetByKey returns the target with the given key.
func TargetByKey(key string) (Target, bool) {
	for _, t := range Targets {
		if t.Key == key {
			return t, true
		}
	}
	return Target{}, false
}

// Stub returns the embedded extractor binary for the target, or an error if it
// has not been generated yet.
func Stub(t Target) ([]byte, error) {
	b, err := stubsFS.ReadFile("stubs/" + t.stubFile())
	if err != nil {
		return nil, fmt.Errorf("stub for %s not built yet — run build/build-stubs.sh (%w)", t.Key, err)
	}
	if len(b) == 0 {
		return nil, fmt.Errorf("stub for %s is empty — re-run build/build-stubs.sh", t.Key)
	}
	return b, nil
}

// Available reports whether a real stub exists for the target.
func Available(t Target) bool {
	b, err := Stub(t)
	return err == nil && len(b) > 0
}
